apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
data:
  DB_POSTGRES_USER: cG9zdGdyZXNxbA==
  DB_POSTGRES_PASSWORD: cG9zdGdyZXNlc2Fz
#kubectl apply -f ecommerce-secret.yml
#echo -n "secretvalue" | base64
