version: "3.2"
services:
  postgresql-master:
    image: bitnami/postgresql-repmgr:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresql_master_data:/bitnami/postgresql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=development_database
      - ALLOW_EMPTY_PASSWORD=yes
      - REPMGR_PRIMARY_ROLE=master
      - REPMGR_PRIMARY_HOST=postgresql-master-1
      - REPMGR_PARTNER_NODES=postgresql-master-1,postgresql-slave-1,postgresql-slave-2
      - REPMGR_NODE_NAME=postgresql-master-1
      - REPMGR_NODE_NETWORK_NAME=postgresql-master-1
      - REPMGR_NODE_ID=1
      - REPMGR_USERNAME=repl_user
      - REPMGR_PASSWORD=repl_user
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgresql-slave1:
    image: bitnami/postgresql-repmgr:latest
    restart: always
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=development_database
      - ALLOW_EMPTY_PASSWORD=yes
      - REPMGR_PRIMARY_HOST=postgresql-master-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_NODE_NAME=postgresql-slave-1
      - REPMGR_NODE_NETWORK_NAME=postgresql-slave-1
      - REPMGR_NODE_ID=2
      - REPMGR_PARTNER_NODES=postgresql-master-1,postgresql-slave-1,postgresql-slave-2
      - REPMGR_USERNAME=repl_user
      - REPMGR_PASSWORD=repl_user
    volumes:
      - postgresql_slave1_data:/bitnami/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgresql-slave2:
    image: bitnami/postgresql-repmgr:latest
    restart: always
    ports:
      - '5434:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=development_database
      - ALLOW_EMPTY_PASSWORD=yes
      - REPMGR_PRIMARY_HOST=postgresql-master-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_NODE_NAME=postgresql-slave-2
      - REPMGR_NODE_NETWORK_NAME=postgresql-slave-2
      - REPMGR_NODE_ID=3
      - REPMGR_PARTNER_NODES=postgresql-master-1,postgresql-slave-1,postgresql-slave-2
      - REPMGR_USERNAME=repl_user
      - REPMGR_PASSWORD=repl_user
    volumes:
      - postgresql_slave2_data:/bitnami/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  haproxy:
    image: haproxy:latest
    ports:
      - "5435:5432"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - postgresql-master
      - postgresql-slave1
      - postgresql-slave2

volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave1_data:
    driver: local
  postgresql_slave2_data:
    driver: local
