replication:
  enabled: true
  replicaCount: 2
  user: replicator
  password: repl_password
  synchronousCommit: "off"
  applicationName: "postgresql-cluster"

primary:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

readReplicas:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

postgresqlUsername: postgres
postgresqlPassword: postgres
postgresqlDatabase: ecommerce
# helm repo update
# helm install postgresql -f postgre-cluster.yml bitnami/postgresql --version 15.5.7 --namespace ecommerce
# helm install postgresql-cluster -f postgre-cluster.yml bitnami/postgresq --namespace ecommerce

#To get the password for "postgres" run:
#export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-cluster -o jsonpath="{.data.postgres-password}" | base64 -d)

#To connect to your database from outside the cluster execute the following commands:
#kubectl port-forward --namespace default svc/postgresql-cluster 5432:5432 &
#PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432

#To connect to your database run the following command:

#kubectl run postgresql-cluster-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:16.3.0-debian-12-r14 --env="PGPASSWORD=$POSTGRES_PASSWORD" \
#  --command -- psql --host postgresql-cluster -U postgres -d postgres -p 5432

#helm uninstall postgresql-cluster --namespace ecommerce

# Kiểm Tra Các PVC Hiện Có
# kubectl get pvc --namespace ecommerce
# Xóa Các PVC
# kubectl delete pvc <pvc_name> --namespace ecommerce
# kubectl delete pvc --namespace ecommerce --all

# kubectl exec -it postgresql-0 --namespace ecommerce -- /bin/bash
