version: '3.0'
services:
  postgres:
    container_name: postgres
    image: postgres:11.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - ecommerce
networks:
  ecommerce:
    driver: bridge
    name: ecommerce
    external: true
