version: '3.2'
services:
  be.ecommerce:
    container_name: be.ecommerce
    image: giabaodocker/be-ecommerce:lastest
    ports:
      - 8081:8081
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_CONNECTION_STRING: Host=postgres;Database=postgres;Username=postgres;Password=postgres
      CLOUDINARY_URL: cloudinary://853652539285151:35dgbXUNu7U4_zye8KiQkR5GagA@hqxqmqmoo
    networks:
      - ecommerce
    depends_on:
      - postgres
    volumes:
      - ./policy.csv:/app/wwwroot/policy.csv
      - ./model.conf:/app/wwwroot/model.conf

  postgres:
    container_name: postgres
    image: postgres:11.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - ecommerce
networks:
  ecommerce:
    driver: bridge
    name: ecommerce
    external: true
