apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRESQL_REPLICATION_PASSWORD: cmVwbF91c2Vy # repl_user (base64 encoded)
  POSTGRESQL_PASSWORD: cG9zdGdyZXM= # postgres (base64 encoded)
