apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ecommerce
  namespace: ecommerce
  labels:
    app: web-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ecommerce
  template:
    metadata:
      labels:
        app: web-ecommerce
    spec:
      containers:
        - name: web-ecommerce
          image: giabaodocker/webapp.net:v.0
          ports:
            - containerPort: 8080
