apiVersion: v1
kind: ConfigMap
metadata:
  name: be-ecommerce-config
  namespace: ecommerce
data:
  policy.csv: |
    # Nội dung của file policy.csv
    p, SuperAdmin, users, list
    p, SuperAdmin, users, create
    p, SuperAdmin, roles, list
    p, SuperAdmin, roles, show
    p, SuperAdmin, roles, edit
    p, SuperAdmin, roles, delete
    p, SuperAdmin, roleclaims, list
    p, SuperAdmin, roleclaims, create
    p, SuperAdmin, roleclaims, show
    p, SuperAdmin, roleclaims, edit
    p, SuperAdmin, roleclaims, delete
    p, Basic, products, list
    p, Basic, products, create
    p, Basic, products, show
    p, Basic, products, edit
    p, Basic, products, delete
    p, Basic, products, create-range
    p, Basic, products, delete-range
    p, Basic, users, list
    p, Basic, product-attributes, list
    p, Basic, product-attributes, create
    p, Basic, product-attributes, show
    p, Basic, product-attributes, edit
    p, Basic, product-attributes, delete
    p, Basic, product-attribute-mappings, list
    p, Basic, product-attribute-mappings, create
    p, Basic, product-attribute-mappings, show
    p, Basic, product-attribute-mappings, edit
    p, Basic, product-attribute-mappings, delete
    p, Basic, product-attribute-values, list
    p, Basic, product-attribute-values, create
    p, Basic, product-attribute-values, edit
    p, Basic, product-attribute-values, show
    p, Basic, product-attribute-values, delete
  model.conf: |
    # Nội dung của file model.conf
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = r.sub == p.sub && r.obj == p.obj && r.act == p.act