apiVersion: v1
kind: Secret
metadata:
  name: be-ecommerce-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRESQL_REPLICATION_PASSWORD: SG9zdD1wb3N0Z3Jlc3FsLW1hc3RlcjtEYXRhYmFzZT1lY29tbWVyY2U7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM=  # repl_user (base64 encoded)
  POSTGRESQL_PASSWORD: Y2xvdWRpbmFyeTovLzg1MzY1MjUzOTI4NTE1MTozNWRnYlhVTnU3VTRfenllOEtpUWtSNUdhZ0FAaHF4cW1xbW9v
  # postgres (base64 encoded)
