apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-ecommerce
  namespace: ecommerce
  labels:
    app: fe-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-ecommerce
  template:
    metadata:
      labels:
        app: fe-ecommerce
    spec:
      containers:
        - name: fe-ecommerce
          image: giabaodocker/fe.ecommerce.local:v.1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_CONNECTION_STRING
              value: "Host=postgresql-master;Database=ecommerce;Username=postgres;Password=postgres"
            - name: POSTGRES_WRITE_CONN_STRING
              value: "Host=postgresql-master;Database=ecommerce;Username=postgres;Password=postgres"
            - name: POSTGRES_READ_CONN_STRING
              value: "Host=postgresql-slave;Database=ecommerce;Username=postgres;Password=postgres"
            - name: CLOUDINARY_URL
              value: "cloudinary://853652539285151:35dgbXUNu7U4_zye8KiQkR5GagA@hqxqmqmoo"
          livenessProbe:
            #  Kiểm tra điểm cuối /healthz của ứng dụng web trên cổng 8081.
            #Nếu điểm cuối này không phản hồi (hoặc phản hồi với trạng thái khác 2xx hoặc 3xx), Kubernetes sẽ khởi động lại container.
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            # Thời gian chờ trước khi thực hiện probe lần đầu tiên.
            periodSeconds: 10
            # Thời gian giữa các lần kiểm tra tiếp theo.
          readinessProbe:
            # Kiểm tra điểm cuối /ready của ứng dụng web trên cổng 8081.
            # Nếu điểm cuối này không phản hồi, container sẽ được coi là chưa sẵn sàng và sẽ không nhận lưu lượng.
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 30
            # Thời gian chờ trước khi thực hiện probe lần đầu tiên.
            periodSeconds: 10
            # Thời gian giữa các lần kiểm tra tiếp theo.
