name: BackEnd.Ecommerce .NET

on:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - backend

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/be.ecommerce

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Ecommerce/Ecommerce.WebApp.Server/Ecommerce.WebApp.Server.csproj

      - name: Build
        run: dotnet build Ecommerce/Ecommerce.WebApp.Server/Ecommerce.WebApp.Server.csproj --no-restore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Ecommerce/Ecommerce.WebApp.Server/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set up kubectl
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        if: github.event_name != 'pull_request'
        run: |
          kubectl apply -f deployments/backend/secret.yml
          kubectl apply -f deployments/backend/deployment.yml
          kubectl apply -f deployments/backend/service.yml

      - name: Update Kubernetes Deployment image
        if: github.event_name != 'pull_request'
        run: |
          kubectl set image deployment/be-ecommerce -n ecommerce be-ecommerce=${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl rollout restart deployment/be-ecommerce -n ecommerce
