# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Ecommerce.WebApp.Razor .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Ecommerce/Ecommerce.WebApp.Server/Ecommerce.WebApp.Server.csproj
      - name: Build
        run: dotnet build Ecommerce/Ecommerce.WebApp.Server/Ecommerce.WebApp.Server.csproj --no-restore

      # - name: Retryable Docker login
      #   id: docker_login
      #   run: |
      #     retries=3
      #     until [ $retries -le 0 ]; do
      #       echo "Logging into Docker Hub..."
      #       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin && break
      #       retries=$((retries - 1))
      #       echo "Retrying Docker login in 10 seconds..."
      #       sleep 10
      #     done
      #   shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker credential helper
        run: |
          mkdir -p ~/.docker
          echo '{ "credsStore": "secretservice" }' > ~/.docker/config.json

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Ecommerce/Ecommerce.WebApp.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-webapp-server:latest
          retries: 3
          retry-delay: 10s
      - name: Set up kubectl
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        if: github.event_name != 'pull_request'
        run: |
          kubectl apply -f deployments/webapp-razor/service.yaml
          kubectl set image deployment/web-ecommerce web-ecommerce=${{ secrets.DOCKER_USERNAME }}/ecommerce-webapp-razor:latest
          kubectl rollout status deployment/web-ecommerce
